### ISSUE TITLE
User can see the daily meals for brekky, lunch, & dinner #1

### ISSUE THREAD

**Issue by bug-smith** [bugass/Cooking-Curiosity#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

the user will be able to click the preview button and the details regarding that meal will be shown.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a website that displays new recipes and meals daily for the different meals in the day.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="324" alt="image" src="https://github.com/bugass/ajax-project/assets/102183396/c3ef8ea7-ff0d-42a2-900d-2ff7b724cdc9">

<img width="316" alt="image" src="https://github.com/bugass/ajax-project/assets/102183396/ac290e41-e63b-4d48-b67b-baab8c2fb3b1">

<img width="782" alt="Screenshot 2023-10-02 at 10 53 45 AM" src="https://github.com/bugass/ajax-project/assets/102183396/8d81eb32-86d7-41e6-b1f4-1c7f99c0f34a">

<img width="781" alt="image" src="https://github.com/bugass/ajax-project/assets/102183396/85306498-aa80-45af-bf8f-0f52fe1d21a4">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] import fonts, js, stylesheets, & images.
- [x] Complete the header HTML
- [x] Complete the header Styling
- [x] Add the body content HTML
- [x] Add the styling for body content CSS
- [x] make a XMLHttpRequest to the RapidAPI food API For, breakfast xhrB, lunch xhrL, and dinner xhrD.
- [x] Create a DOM tree for the click event of preview per meal IE. 3 dom trees. to pull in the data from the api calls
- [x] Show the meals, Data, IE breakfast preview "click", show breakfast.
- [x] Clean all extra/excess styling 
- [x] Confirm functionality, the meals should be showing and hiding on preview click.
