### ISSUE TITLE
User can add a favorite meal or meals

### ISSUE THREAD

**Issue by bug-smith** [bugass/Cooking-Curiosity#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user can click a heart icon and add the meal to a list of favorites, based on meal type.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user is able to see their favorites based on brekky, lunch, dinner.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="324" alt="Screenshot 2023-10-02 at 11 50 06 AM" src="https://github.com/bugass/ajax-project/assets/102183396/5c47854d-400e-4141-b98f-71bfaf2c54c4">

<img width="456" alt="Screenshot 2023-10-02 at 11 50 31 AM" src="https://github.com/bugass/ajax-project/assets/102183396/4d88093c-0e1f-47ca-abc1-1923c86bf93d">

<img width="784" alt="Screenshot 2023-10-02 at 11 53 33 AM" src="https://github.com/bugass/ajax-project/assets/102183396/72c52480-57fc-4935-9141-26efd928cb3c">

<img width="786" alt="Screenshot 2023-10-02 at 11 53 39 AM" src="https://github.com/bugass/ajax-project/assets/102183396/672a419b-406d-4840-84d9-710d80df1818">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add the heart icon (represents favoriting) to the respective spots
- [x] Add a handler for the heart icon to add the previewed meal to the favorite list.
- [x] Create the HTML & CSS for the favorites table, and update the body to have a dropdown selection for the type of meal.
- [x] Add a view swap function to the favorites header to swap views to the favorite table.
- [x] Add a handler to the dropdown to show the selected meal types. IE only shows brekky meals if breakfast is selected.
- [x] Clean all extra Styling.
- [x] confirm functionality is correct, with the favorites being added to the table and the view swap working.
