### ISSUE TITLE
User is able to see meal info of favorited meals

### ISSUE THREAD

**Issue by bug-smith** [bugass/Cooking-Curiosity#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user will be able to see the meal info of the favorited meal in the table of meals.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will click the meal info button, and it will display the info regarding instructions and ingredients to complete.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="481" alt="image" src="https://github.com/bugass/ajax-project/assets/102183396/85441cc7-e147-46a5-8028-c1b031619fe8">

<img width="301" alt="image" src="https://github.com/bugass/ajax-project/assets/102183396/4635cc03-099e-47c5-b592-9d18830fa7f4">

<img width="785" alt="image" src="https://github.com/bugass/ajax-project/assets/102183396/a891c06f-c4b6-4c68-8553-adc41490e7f8">

<img width="282" alt="image" src="https://github.com/bugass/ajax-project/assets/102183396/21e3f99c-72fe-432b-94c3-23acf3b1a77c">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Add meal info button to the favorite table
- [ ] event listener for the view swap to show the main page with the favorited meals info showing.
- [ ] preview click will hide the saved favorite & reset to show today's meal
- [ ] clean all css
