### ISSUE TITLE
User can add a note to the favorited meal

### ISSUE THREAD

**Issue by bug-smith** [bugass/Cooking-Curiosity#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user can add any notes to the meal as they wish.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

the user will have a button to click, a modal will be produced with a textarea for entry, & two buttons to save/leave the modal.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="303" alt="image" src="https://github.com/bugass/ajax-project/assets/102183396/8310b509-d34f-4ca6-b062-7d2d29463fa3">

<img width="786" alt="image" src="https://github.com/bugass/ajax-project/assets/102183396/9da02943-de35-419b-b7a0-cdae678d7280">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Add HTML to the favorite table to show the notes button.
- [ ] Create a modal on click, to show an HTML example.
- [ ] User clicks back, hides modal.
- [ ] User clicks Save, the text within the text area will be saved and stored in the object within the table
- [ ] clean up all CSS
